# Generated by Django 3.0.7 on 2020-08-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('singer', models.CharField(max_length=20)),
                ('tags', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='documents')),
                ('song', models.FileField(upload_to='documents')),
            ],
        ),
    ]
