# Generated by Django 3.0.7 on 2020-09-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20200831_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='movie',
            field=models.CharField(default='', max_length=20),
        ),
    ]
